const std = @import("std");
const cpu = @import("cpu");

// IMPORTANT NOTE:
// all unit tests are generated by Claude

test "NOP instruction" {
    var c = cpu.CPU{};
    const initial_pc = c.pc;
    c.memory[0] = 0x00;

    try c.step();

    try std.testing.expectEqual(initial_pc + 1, c.pc);
}

test "LD (BC), A instruction" {
    var c = cpu.CPU{};
    c.a = 0x42;
    c.b = 0x80;
    c.c = 0x00;
    c.memory[0] = 0x02;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x42), c.memory[0x8000]);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "LD B, n instruction" {
    var c = cpu.CPU{};
    c.memory[0] = 0x06;
    c.memory[1] = 0x42;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x42), c.b);
    try std.testing.expectEqual(@as(u16, 2), c.pc);
}

test "LD (DE), A instruction" {
    var c = cpu.CPU{};
    c.a = 0x55;
    c.d = 0x90;
    c.e = 0x10;
    c.memory[0] = 0x12;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x55), c.memory[0x9010]);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "LD BC, d16 instruction" {
    var c = cpu.CPU{};
    c.memory[0] = 0x01;
    c.memory[1] = 0x34; // Low byte
    c.memory[2] = 0x12; // High byte

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x12), c.b);
    try std.testing.expectEqual(@as(u8, 0x34), c.c);
    try std.testing.expectEqual(@as(u16, 3), c.pc);
}

test "LD A, (BC) instruction" {
    var c = cpu.CPU{};
    c.b = 0x80;
    c.c = 0x50;
    c.memory[0] = 0x0A;
    c.memory[0x8050] = 0x99;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x99), c.a);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "LD C, d8 instruction" {
    var c = cpu.CPU{};
    c.memory[0] = 0x0E;
    c.memory[1] = 0x77;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x77), c.c);
    try std.testing.expectEqual(@as(u16, 2), c.pc);
}

test "LD D, d8 instruction (0x16)" {
    var c = cpu.CPU{};
    c.memory[0] = 0x16;
    c.memory[1] = 0xAA;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0xAA), c.d);
    try std.testing.expectEqual(@as(u16, 2), c.pc);
}

test "NOP instruction advances PC correctly" {
    var c = cpu.CPU{};
    c.pc = 0x1000;
    c.memory[0x1000] = 0x00;

    try c.step();

    try std.testing.expectEqual(@as(u16, 0x1001), c.pc);
}

test "LD (BC), A with different addresses" {
    var c = cpu.CPU{};
    c.a = 0xFF;
    c.b = 0x20;
    c.c = 0x30;
    c.memory[0] = 0x02;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0xFF), c.memory[0x2030]);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "LD B, n with boundary values" {
    var c = cpu.CPU{};
    c.memory[0] = 0x06;
    c.memory[1] = 0x00; // Test zero value

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x00), c.b);
    try std.testing.expectEqual(@as(u16, 2), c.pc);

    // Test with 0xFF
    c.pc = 0;
    c.memory[1] = 0xFF;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0xFF), c.b);
    try std.testing.expectEqual(@as(u16, 2), c.pc);
}

test "Multiple instructions in sequence" {
    var c = cpu.CPU{};

    // Set up a sequence: LD B, 0x10 -> LD C, 0x20 -> LD (BC), A
    c.a = 0x88;
    c.memory[0] = 0x06; // LD B, n
    c.memory[1] = 0x10;
    c.memory[2] = 0x0E; // LD C, n
    c.memory[3] = 0x20;
    c.memory[4] = 0x02; // LD (BC), A

    try c.step(); // LD B, 0x10
    try std.testing.expectEqual(@as(u8, 0x10), c.b);
    try std.testing.expectEqual(@as(u16, 2), c.pc);

    try c.step(); // LD C, 0x20
    try std.testing.expectEqual(@as(u8, 0x20), c.c);
    try std.testing.expectEqual(@as(u16, 4), c.pc);

    try c.step(); // LD (BC), A
    try std.testing.expectEqual(@as(u8, 0x88), c.memory[0x1020]);
    try std.testing.expectEqual(@as(u16, 5), c.pc);
}

test "LD A, (DE) instruction" {
    var c = cpu.CPU{};
    c.d = 0x40;
    c.e = 0x80;
    c.memory[0] = 0x1A;
    c.memory[0x4080] = 0xCC;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0xCC), c.a);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "LD E, d8 instruction" {
    var c = cpu.CPU{};
    c.memory[0] = 0x1E;
    c.memory[1] = 0x5A;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x5A), c.e);
    try std.testing.expectEqual(@as(u16, 2), c.pc);
}

test "LD H, d8 instruction" {
    var c = cpu.CPU{};
    c.memory[0] = 0x26;
    c.memory[1] = 0xB3;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0xB3), c.h);
    try std.testing.expectEqual(@as(u16, 2), c.pc);
}

test "LD L, d8 instruction" {
    var c = cpu.CPU{};
    c.memory[0] = 0x2E;
    c.memory[1] = 0x7F;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x7F), c.l);
    try std.testing.expectEqual(@as(u16, 2), c.pc);
}

test "INC B instruction" {
    var c = cpu.CPU{};
    c.b = 0x10;
    c.memory[0] = 0x04;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x11), c.b);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "INC B instruction with overflow" {
    var c = cpu.CPU{};
    c.b = 0xFF;
    c.memory[0] = 0x04;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x00), c.b);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "DEC B instruction" {
    var c = cpu.CPU{};
    c.b = 0x10;
    c.memory[0] = 0x05;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x0F), c.b);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "DEC B instruction with underflow" {
    var c = cpu.CPU{};
    c.b = 0x00;
    c.memory[0] = 0x05;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0xFF), c.b);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "INC BC instruction" {
    var c = cpu.CPU{};
    c.b = 0x10;
    c.c = 0xFF;
    c.memory[0] = 0x03;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x11), c.b);
    try std.testing.expectEqual(@as(u8, 0x00), c.c);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "DEC BC instruction" {
    var c = cpu.CPU{};
    c.b = 0x11;
    c.c = 0x00;
    c.memory[0] = 0x0B;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x10), c.b);
    try std.testing.expectEqual(@as(u8, 0xFF), c.c);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "ADD HL, BC instruction" {
    var c = cpu.CPU{};
    c.h = 0x10;
    c.l = 0x00;
    c.b = 0x00;
    c.c = 0x50;
    c.memory[0] = 0x09;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x10), c.h);
    try std.testing.expectEqual(@as(u8, 0x50), c.l);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "LD (HL+), A instruction" {
    var c = cpu.CPU{};
    c.a = 0x42;
    c.h = 0x80;
    c.l = 0x00;
    c.memory[0] = 0x22;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x42), c.memory[0x8000]);
    try std.testing.expectEqual(@as(u8, 0x80), c.h);
    try std.testing.expectEqual(@as(u8, 0x01), c.l);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "LD A, (HL+) instruction" {
    var c = cpu.CPU{};
    c.h = 0x70;
    c.l = 0x50;
    c.memory[0] = 0x2A;
    c.memory[0x7050] = 0x88;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x88), c.a);
    try std.testing.expectEqual(@as(u8, 0x70), c.h);
    try std.testing.expectEqual(@as(u8, 0x51), c.l);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "LD (HL-), A instruction" {
    var c = cpu.CPU{};
    c.a = 0x99;
    c.h = 0x60;
    c.l = 0x01;
    c.memory[0] = 0x32;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0x99), c.memory[0x6001]);
    try std.testing.expectEqual(@as(u8, 0x60), c.h);
    try std.testing.expectEqual(@as(u8, 0x00), c.l);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}

test "LD A, (HL-) instruction" {
    var c = cpu.CPU{};
    c.h = 0x50;
    c.l = 0x10;
    c.memory[0] = 0x3A;
    c.memory[0x5010] = 0xDD;

    try c.step();

    try std.testing.expectEqual(@as(u8, 0xDD), c.a);
    try std.testing.expectEqual(@as(u8, 0x50), c.h);
    try std.testing.expectEqual(@as(u8, 0x0F), c.l);
    try std.testing.expectEqual(@as(u16, 1), c.pc);
}